#!/bin/bash
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White
Color_Off='\033[0m'       # Text Reset
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

if [ $USER != root ]
	then echo -e "$Red[x]You Don't have root user privileges${Color_Off}"
	exit
else
	clear

INSTALLING_ERROR="[${Red}x${Color_Off}]Error while installing requierd tools!"
DEBIAN_INSTALL="apt-get -qq install $1"
DEBIAN_TOOLS=( "dnsmasq" "hostapd" "iw" "wvdial" "bridge-utils" "macchanger" "mdk3" "openssl" "aircrack-ng" "iptables" "vde2" "reaver" "apache2" "beef-xss" "xterm" "arp-scan" "maclookup" )
ARCH_INSTALL="pacman -S --noconfirm $1"
ARCH_TOOLS=( "dnsmasq" "hostapd" "iw" "wvdial" "bridge-utils" "macchanger" "mdk3" "openssl" "aircrack-ng" "iptables" "vde2" "reaver" "apache" "beef" "xterm" "arp-scan" "maclookup" )


function debian_error {
	echo -e $INSTALLING_ERROR
	echo -e "\n[${Yellow}!${Color_Off}]${Cyan}Looks like a requierd tool wasn't found in your repositories .. ${Green}We highly recommend to add kali linux repositories temporary to install the requierd tools then we will remove it${Color_Off}"
	printf "\n[${Blue}?${Color_Off}]Accept?(y/n) "
	read REPO_ADD
	if [[ $REPO_ADD == "y" ]]; then
		echo -e "[${Green}+${Color_Off}]Adding the repositories.."
		apt-key adv --keyserver pgp.mit.edu --recv-keys ED444FF07D8D0BF6
		echo "#Kali Repos -- Added by deadlysignals --" >> /etc/apt/sources.list
		echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" >> /etc/apt/sources.list
		apt-get -qq update
	else
		echo -e "[${Red}x${Color_Off}]Exiting..";exit 1
	fi
}

function arch_error {
	echo -e $INSTALLING_ERROR
	echo -e "\n[${Yellow}!${Color_Off}]${Cyan}Looks like a requierd tool wasn't found in your repositories .. ${Green}We highly recommend to add blackarch repositories temporary to install the requierd tools${Color_Off}"
	printf "\n[${Blue}?${Color_Off}]Accept?(y/n) "
	read REPO_ADD
	if [[ $REPO_ADD == "y" ]];then
			echo -e "[${Green}+${Color_Off}]Adding the repositories.."
			curl -O https://blackarch.org/strap.sh;chmod 777 strap.sh;./strap.sh
			pacman -Syy

	else
			echo -e "[${Red}x${Color_Off}]Exiting..";exit 1
	fi
}
	echo -e """$Yellow
  _____              _          _  _  _                     
 |_   _|            | |        | || |(_)                    
   | |   _ __   ___ | |_  __ _ | || | _  _ __    __ _       
   | |  |  _ \ / __|| __|/ _  || || || ||  _ \  / _  |      
  _| |_ | | | |\__ \| |_| (_| || || || || | | || (_| | _  _ 
 |_____||_| |_||___/ \__|\__,_||_||_||_||_| |_| \__, |(_)(_)
                                                 __/ |      
                                                |___/      
		$Red<$Color_Off Tool Information $Red>$Color_Off
	
	[$Cyan 1 $Color_Off]$Blue Tool Name $Red:$Color_Off Deadly Signals
	[$Cyan 2 $Color_Off]$Blue Version   $Red:$Color_Off 4.0
	[$Cyan 3 $Color_Off]$Blue Coded By  $Red:$Color_Off 0V3RK!113R
	[$Cyan 4 $Color_Off]$Blue Tool Type $Red:$Color_Off Fake Access Point Attack


	"""
	echo -e "[${Blue}*${Color_Off}]We gonne install some tools to your system\n"
	read -p "Continue? (y,n): " yn

		## Run Debian installation ##

	if [ -d /etc/apt ]
		then
		echo -e "[${Green}+${Color_Off}]system : ${Blue}Debian${Color_Off}"

		case $yn in
		[Yy]* )
			#update
			echo -e "[${BBlue}*${Color_Off}]Updating repositories..\n"
			sleep 1
			echo -e "[${Yellow}!${Color_Off}]it may take some time\n"
			apt-get -qq update
			if [[ $? != 0 ]]; then echo -e "[${Red}x${Color_Off}]Error while updating your repositories!";exit 1;fi

			## INSTALLING ##
			for debian_tool in ${DEBIAN_TOOLS[@]};do
					echo -e "[${BBlue}*${Color_Off}]Install $debian_tool" ;$DEBIAN_INSTALL $debian_tool
					if [[ $? != 0 ]];then debian_error;$DEBIAN_INSTALL $debian_tool;fi
			done
			
			echo -e "[${BBlue}*${Color_Off}]Installing the tool"
			chmod 777 deadlysignals
			more /etc/apt/sources.list | grep 'Added by deadlysignals' > /dev/null
			if [[ $? -eq 0 ]]; then sed -i '/Added by deadlysignals/d' /etc/apt/sources.list;sed -i '/kali/d' /etc/apt/sources.list;fi

			echo -e "[${Green}+${Color_Off}]Tool has been installed successfully!\n"
			echo -e "[${Yellow}!${Color_Off}]You can run the tool by typing ${Yellow}sudo ./deadlysignals${Color_Off}"
			exit 0;;
		[Nn]* )
			echo -e "[${Red}x${Color_Off}]Exiting.."
			exit 0;;
		* )
			echo "y = yes , n = no"
			exit 1;;
		esac
	fi

		## Run Arch Installaton ##
	if [ -d /etc/pacman.d ]
		then
		echo -e "[${Green}+${Color_Off}]system : ${Red}Arch${Color_Off}"
		case $yn in
			[Yy]* )
				#update
				echo -e "[${BBlue}*${Color_Off}]Updating respositories.."
				pacman -Syy
				if [ $? != 0 ];then exit 1;fi
				#installing
				for arch_tool in ${ARCH_TOOLS[@]};do
						echo -e "[${BBlue}*${Color_Off}]Install $arch_tool"
						pacman -Qs $arch_tool > /dev/null
						if [[ $? != 0 ]];then
							$ARCH_INSTALL $arch_tool
							if [ $? != 0 ];then echo -e $INSTALLING_ERROR;arch_error;$ARCH_INSTALL $arch_tool;fi
						fi
				done
				
				#install tool
				echo -e "[${BBlue}*${Color_Off}]Installing the tool"
				chmod 777 deadlysignals
				echo -e "[${Green}+${Color_Off}]Tool has been installed successfully!\n"
				echo -e "[${Yellow}!${Color_Off}]You can run the tool by typing ${Yellow}sudo ./deadlysignals${Color_Off}"
				exit 0;;
			[Nn]* )
				echo -e "[${Red}x${Color_Off}]Exiting.."
				exit 0;;
			* )
				echo "y = yes , n = no"
				exit 1;;
		esac
	fi
fi
