#!/bin/bash
## Colors ##
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White
Color_Off='\033[0m'       # Text Reset
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

function banner {
	echo -e """ ${Purple}
	 __               __              
	|  \ _ _  _||    (_ . _  _  _ | _ 
	|__/(-(_|(_||\/  __)|(_)| )(_||_) 
	             /       _/           
	  	${Green}Connection Board

	${Color_Off}\n"""
}

function board_info {
	#ap_name=$(awk -F'"' '/^APNAME=/ {print $2}' deadlysignals )
	SIGNAL_NAME=($(more .signalname))
	echo -e "[${BBlue}*${Color_Off}]Access Point name ${Purple}  :${Color_Off} $SIGNAL_NAME" ## PUT THE NAME HERE! ##
	echo -e "[${BBlue}*${Color_Off}]Gateway IP ${Purple}         :${Color_Off} 10.0.0.1" 
}

function connected_devices {
	#source deadlysignals
	banner
	board_info
	DEVICE_IP=($(nmap -PR -sn -n -oG - 10.0.0.2-255 2>&1 | grep Host | awk '{print $2}'))
	touch .attemptsip
	if  grep -Fxq "$DEVICE_IP" .attemptsip
		then sleep 0.0 #Shut_up
	else
		echo $DEVICE_IP >> .attemptsip
	fi
	ATTEMPTS=($(more .attemptsip | sed '/^\s*$/d' | wc -l))
	echo -e "[${BBlue}*${Color_Off}]Connection Attempts ${Purple}:${BRed} $ATTEMPTS${Color_Off}"
	echo
	echo "---------------------------------------------------"
	echo "Device IP   |   Device MAC Address   |  Device Name"
	for devices in "${DEVICE_IP[@]}";do
		echo
		printf "\e[0;33m$devices     "
		DEVICE_MAC=($(nmap -PR -sn -n $devices 2>&1 | grep -i mac | awk '{print $3}' | tr [:upper:] [:lower:]))
		
		for mac in "${DEVICE_MAC[@]}";do
			printf "  \e[0;32m$mac    "
			DEVICE_MAC_NAME=`curl -s http://api.macvendors.com/$mac`
			for mac_name in "${DEVICE_MAC_NAME[@]}";do
				printf "  \e[0;34m$mac_name\e\033[0m"
			done
		done
	done
}
connected_devices
