#!/bin/bash
## Colors ##
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White
Color_Off='\033[0m'       # Text Reset
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

arp-scan --interface $1 10.0.0.1/24 | sed '/Interface/d;/WARNING/d;/Starting/d;/kernel/d;/arp-scan/d' > arp
echo
devices=$(more arp | awk '{print $1}' | sort -u)
#gateway=$( more arp | grep -i gateway | awk '{print $2}' | sed -e 's/(//g' | sed -e 's/)//g')
device_mac=$(more arp | awk '{print $2}' | sort -u)
hex_chars=$(more arp | awk '{print $2}' | sed -e 's/\:/\-/g' | tr [:lower:] [:upper:] | sed -e 's/^\(.\{8\}\).*/\1/' | sort -u)
more arp >> .attemptsip
attempts=$(more .attemptsip | awk '{print $2}' | sort -u | sed '/^$/d' | wc -l)
###################################################################33
echo -e """ ${Purple}
 __               __
|  \ _ _  _||    (_ . _  _  _ | _
|__/(-(_|(_||\/  __)|(_)| )(_||_)
	     /       _/
    ${Green}Connection Board${Color_Off}\n"""

echo -e "${White}[${Red}*${Color_Off}${White}]Attempts: ${Green}$attempts${White} "
echo -e """${White}----------------------------------------------------------------
${Blue}Device IP   ${Yellow} |   ${Blue}Device MAC Address	${Yellow}|   ${Blue}Device Name ${Green}
"""
echo -e "${Purple}"
for device in ${devices[@]};do 
		printf "$devices   	   "
		for mac in ${device_mac[@]};do
				printf "$mac"
				for name in ${hex_chars};do
						more /usr/share/maclookup/oui.txt | grep $name | sed -e 's/(hex)//g' | cut -d" " -f4-30
						echo
				done
		done
done
